In [181]:
import random
import matplotlib.pyplot as plt

In [182]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA

In [183]:
linguistic_variable = "linguistic variable"
Paramerters_S = "S"
Paramerters_M = "M"
y = "y"
type_Fuzzy_Set = "fuzzy set"
rule = "rule"   
structure = 'structure'
being = 'being'
not_list = 'not_list'
term_choice = 'term_choice'
elements = 'elements'
fitness = 'fitness'
gens = 'gens'
gen_num = 5
Max_S = 70   # 2 * 35   # calcualte the database
Min_S = 0
Max_M = 7    # 2*5
Min_M = -11  # 2*-5
element_num = 10
max_num_of_features = 5
linguistic = ["very low", "low", "medium", "high", "very high"]
num_of_chromosomes = 50
num_of_generations = 100
crossover_rate = 0.8
mutation_rate = 0.2
chart_fitness = []

In [184]:
def chart():
    # Generate x-axis values using range() function
    x = range(len(chart_fitness))

    # Create line plot
    plt.plot(x, chart_fitness)

    # Add labels and title
    plt.xlabel('Index')
    plt.ylabel('fitness')
    plt.title('fitness of chromosome')

    # Show the plot
    plt.show()

In [185]:
# read and pre process the data set
def process_data(sms_data_str):
    """
    convert `sms_data_str` into a pandas dataframe
    """
    data_arr = []

    data_records = sms_data_str.split('\n')[:-1]
    for data in data_records:
        label = None
        sample = None
        data_type = data[:3]
        if data_type == 'ham':
            label = 'legitimate'
            sample = data[4:]
        elif data_type == 'spa':
            label = 'spam'
            sample = data[5:]
        else:
            label = 'N/A'

        data_arr.append([label, sample])

    data_arr = np.array(data_arr)
    data_label = data_arr[:, 0]
    data_records = data_arr[:, 1]

    return data_records, data_label
# extract feature from SMS


def tfidf_vectorizer(records):
    vectorizer = TfidfVectorizer(
        lowercase=True,
        token_pattern=r'\b[A-Za-z]+\b',
        norm=None
    )

    records_transformed = vectorizer.fit_transform(records)

    return records_transformed.toarray(), vectorizer.get_feature_names_out()


# decrece the dimension
def feature_extraction(X, n_components=5):
    reduction_pca = PCA(
        n_components=n_components,
        whiten=False
    )
    data_reduced = reduction_pca.fit_transform(X)
    return data_reduced

# select the feature


def feature_selection(df_records, labels, n_components=5):
    feature_selection_model = SelectKBest(mutual_info_classif, k=n_components)
    # make a selection over the best features
    selected_record_features = feature_selection_model.fit_transform(
        df_records, labels)

    return selected_record_features, feature_selection_model.get_feature_names_out()

In [186]:
# read data
sms_data_str = None
with open('SMSSpamCollection') as file:
    sms_data_str = file.read()

In [187]:
# extract feature
records, labels = process_data(sms_data_str)
records_vectorized, feature_names = tfidf_vectorizer(records)

# one hot encoding labels (convert label to 0 or 1)
labels = np.array([0 if y == 'legitimate' else 1 for y in labels])

# reducing dimension
records_dim_reduced = feature_extraction(records_vectorized)

In [216]:
print(records_dim_reduced)
print(type(records_dim_reduced))
len(records_dim_reduced)

[[-1.85535132  0.28168783 -1.18337054  0.82514429  0.73044111]
 [-2.78244021  0.5193157  -1.74198437  0.49980828 -0.74358069]
 [ 0.49179674 -0.04311256  2.0202674  -6.51301317  1.03129434]
 ...
 [-0.86666156 -0.05145575 -0.21573774  0.81191154  0.731563  ]
 [ 4.0193264   0.16103729 -1.33430384 -0.29366753  1.12894774]
 [-2.03289081  0.38329974  0.20039571 -0.08751409  0.16293072]]
<class 'numpy.ndarray'>


5574

In [188]:
# read data
# open the file for reading
labels = []
with open('SMSSpamCollection', 'r') as f:

    for line in f:
        # split the line into words
        words = line.split()
        # select the first word
        first_word = words[0]
        if words[0] == 'ham':
            labels.append(0)
        else:
            labels.append(1)

print(labels)
# find number of zero in labels
print(labels.count(0))
# find number of one in labels
print(labels.count(1))

# find the index of zero in labels
zero_index = [i for i, x in enumerate(labels) if x == 1]
print(zero_index)
# find the index of one in labels
one_index = [i for i, x in enumerate(labels) if x == 0]

[0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [189]:
# This function creates a list of chromosomes.
def create_chromosomes(num_chromosomes):
    # Initialize an empty list to store the chromosomes.
    chromosomes = []
    
    # For each chromosome:
    for i in range(num_chromosomes):
        # Initialize an empty dictionary to store this chromosome's genetic material.
        chro = dict()
        chro[structure] = []
        # For each genetic element (gene) in the chromosome:
        for _ in range(gen_num):
            # Initialize an empty dictionary to store this gene's features (linguistic variable, parameter S, parameter M, and type of fuzzy set).
            gen = dict()
            # Generate a random number between 3 and 5 to determine the number of linguistic variables in this feature.
            num_feature = random.randint(3, 5)
            # For each linguistic variable in this feature, randomly choose one from the set of possible linguistic variables and add it to the list of linguistic variables in this feature.
            gen[linguistic_variable] = [random.choice(linguistic) for i in range(num_feature)]
            # For each parameter S in this feature, randomly generate a floating-point number between Min_S and Max_S and add it to the list of S parameters in this feature.
            gen[Paramerters_S] = [random.uniform(Min_S, Max_S) for i in range(num_feature)]
            # For each parameter M in this feature, randomly generate a floating-point number between Min_M and Max_M and add it to the list of M parameters in this feature.
            gen[Paramerters_M] = [random.uniform(Min_M, Max_M) for i in range(num_feature)]
            # For each type of fuzzy set in this feature, randomly generate an integer between 1 and 4 and add it to the list of fuzzy set types in this feature.
            gen[type_Fuzzy_Set] = [random.randint(1, 4) for i in range(num_feature)]
            # Add the current gene (with its features) to this chromosome.
            chro[structure].append(gen)
        
        # Initialize an empty dictionary to store the rule for this chromosome's genetic material.
        gen_rule = dict()
        # For each genetic element (gene) in the chromosome:
        gen_rule[being] = [random.choice([0, 1]) for i in range(gen_num)]     # 1 ==> be   0 ==> not be
        gen_rule[not_list] = [random.choice([0, 1]) for i in range(gen_num)]  # 1 ==> NOT   0 ==> self
        gen_rule[term_choice] = [random.choice(chro[structure][i][linguistic_variable]) for i in range(gen_num)]   # which term?
        gen_rule[y] = random.choice([0, 1])   # spam or ham
        # Add the rule to this chromosome.
        chro[rule] = gen_rule  
        
        chro[fitness] = 0
        # Add this chromosome (with its genetic material and rule) to the list of chromosomes.
        chromosomes.append(chro)
        
    # Return the list of chromosomes.
    return chromosomes

In [190]:
chro = create_chromosomes(2)
print(len(chro[0]))
# print(chro[0][structure][0][linguistic_variable])
# print(chro[1][structure][0])

parent1 = chro[0]
parent2 = chro[1]

#print(chro[0][structure][0][Paramerters_S])
#print(chro[0][structure][1][Paramerters_S])
# print(parent1)
# print(parent2)
# parent1_linguistic = chro[0][structure][0][linguistic_variable]
# parent2_linguistic = chro[1][structure][0][linguistic_variable]

# parent1_S = chro[0][structure][0][Paramerters_S]
# parent2_S = chro[1][structure][0][Paramerters_S]

# parent1_M = chro[0][structure][0][Paramerters_M]
# parent2_M = chro[1][structure][0][Paramerters_M]

# parent1_fuzzy = chro[0][structure][0][type_Fuzzy_Set]
# parent2_fuzzy = chro[1][structure][0][type_Fuzzy_Set]

# parent1_bein = chro[0][rule][being]
# parent2_bein = chro[1][rule][being]

# parent1_not_list = chro[0][rule][not_list]
# parent2_not_list = chro[1][rule][not_list]

# parent1_term_choice = chro[0][rule][term_choice]
# parent2_term_choice = chro[1][rule][term_choice]


3


In [191]:
# This function takes in two parents (sequences) and creates two offsprings by performing a continuous crossover.
def crossover_continuous(parent1, parent2):    
    # Set the alpha value for the crossover.
    alpha = 0.25
    offspring1 = []
    offspring2 = []
    # If the first sequence is longer than the second one:
    if len(parent1) > len(parent2):
        # Generate a list of random indexes for the shorter sequence.
        indexes = random.sample(range(len(parent1)), len(parent2))
        # For each index in the shorter parent: if the corresponding element in the longer parent is greater, perform a crossover calculation using alpha and add the results to offspring1 and offspring2. Otherwise, perform the calculation using the reverse order and add the results to offspring1 and offspring2.
        for i in range(len(parent2)):
            if parent2[i] > parent1[indexes[i]]:
                distance = parent2[i] - parent1[indexes[i]]
                offspring1.append(parent1[indexes[i]] + alpha * distance)
                offspring2.append(parent2[i] - alpha * distance)
            else:
                distance = parent1[indexes[i]] - parent2[i]
                offspring1.append(parent2[i] + alpha * distance)
                offspring2.append(parent1[indexes[i]] - alpha * distance)
                
        # Add the remaining elements of the longer parent to the first offspring.     
        temp = [item for item in [_ for _ in range(len(parent2))] if item not in indexes]
        for i in range(len(temp)):
            offspring1.append(parent1[temp[i]])
        
    # If the second sequence is longer than or the same length as the first one:
    else:
        # Generate a list of random indexes for the shorter sequence.
        indexes = random.sample(range(len(parent2)), len(parent1))
        # For each index in the shorter parent: if the corresponding element in the longer parent is greater, perform a crossover calculation using alpha and add the results to offspring1 and offspring2. Otherwise, perform the calculation using the reverse order and add the results to offspring1 and offspring2.
        for i in range(len(parent1)):
            if parent1[i] > parent2[indexes[i]]:
                distance = parent1[i] - parent2[indexes[i]]
                offspring1.append(parent2[indexes[i]] + alpha * distance)
                offspring2.append(parent1[i] - alpha * distance)
            else:
                distance = parent2[indexes[i]] - parent1[i]
                offspring1.append(parent1[i] + alpha * distance)
                offspring2.append(parent2[indexes[i]] - alpha * distance)
                
        # Add the remaining elements of the longer parent to the second offspring. 
        temp = [item for item in [_ for _ in range(len(parent2))] if item not in indexes]
        for i in range(len(temp)):
            offspring2.append(parent2[temp[i]])
    
    # Return the two new offspring.
    return offspring1, offspring2

In [192]:
# This function takes in two parents (sequences) and creates two offsprings by performing a discrete crossover.
def crossover_discrete(parent1, parent2):   
    offspring1 = []
    offspring2 = []
    # If the first sequence is longer than the second one:
    if len(parent1) > len(parent2):
        # Generate a list of random indexes for the shorter sequence.
        indexes = random.sample(range(len(parent1)), len(parent2))
        # For each index in parent1: if it's in indexes, add the corresponding element to offspring2. Otherwise, add it to offspring1. 
        for i in range(len(parent1)):
            if i in indexes:
                offspring2.append(parent1[i])
            else:
                offspring1.append(parent1[i])
        # Add all of parent2 to offspring1.
        offspring1.extend(parent2)     
    # If the second sequence is longer than or the same length as the first one:
    else:
        # Generate a list of random indexes for the shorter sequence.
        indexes = random.sample(range(len(parent2)), len(parent1))
        # For each index in parent2: if it's in indexes, add the corresponding element to offspring1. Otherwise, add it to offspring2. 
        for i in range(len(parent2)):
            if i in indexes:
                offspring1.append(parent2[i])
            else:
                offspring2.append(parent2[i])
        # Add all of parent1 to offspring2.
        offspring2.extend(parent1)
    
    # Return the two new offspring.
    return offspring1, offspring2 


In [193]:
def crossover_term_choice(parent1, parent2):
    child1, child2 = crossover_discrete(parent1[rule][term_choice], parent2[rule][term_choice])
    for i in range(len(child1)):
        if child1[i] not in parent1[structure][i][linguistic_variable]:
            child1[i] = random.choice(parent1[structure][i][linguistic_variable])
    
    for i in range(len(child2)):
        if child2[i] not in parent2[structure][i][linguistic_variable]:
            child2[i] = random.choice(parent2[structure][i][linguistic_variable])
    
    return child1, child2

In [194]:
def crossover(parent1, parent2):
    structure1 = [dict() for i in range(max_num_of_features)]
    structure2 = [dict() for i in range(max_num_of_features)]
    
    for i in range(max_num_of_features):
        structure1[i][linguistic_variable], structure2[i][linguistic_variable] = crossover_discrete(parent1[structure][i][linguistic_variable], parent2[structure][i][linguistic_variable])
        structure1[i][type_Fuzzy_Set], structure2[i][type_Fuzzy_Set] = crossover_discrete(parent1[structure][i][type_Fuzzy_Set], parent2[structure][i][type_Fuzzy_Set])
        structure1[i][Paramerters_M], structure2[i][Paramerters_M] = crossover_continuous(parent1[structure][i][Paramerters_M], parent2[structure][i][Paramerters_M])
        structure1[i][Paramerters_S], structure2[i][Paramerters_S] = crossover_continuous(parent1[structure][i][Paramerters_S], parent2[structure][i][Paramerters_S])
    
    
    rule1 = dict()
    rule2 = dict()
    
    rule1[being], rule2[being] = crossover_discrete(parent1[rule][being], parent2[rule][being])
    rule1[not_list], rule2[not_list] = crossover_discrete(parent1[rule][not_list], parent2[rule][not_list])
    rule1[term_choice], rule2[term_choice] = crossover_term_choice(parent1, parent2)
    
    rule1[y], rule2[y] = parent2[rule][y], parent1[rule][y]
    
    offspring1 = dict()
    offspring1[structure] = structure1
    offspring1[rule] = rule1
    
    offspring2 = dict()
    offspring2[structure] = structure2
    offspring2[rule] = rule2
    
    return offspring1, offspring2

In [195]:
def mutation_linguistic(parent):
    for i in range(len(parent)):
        if random.uniform(0, 1) < mutation_rate:
            parent[i] = random.choice(linguistic)   
        else:
            pass
    return parent

In [196]:
def mutation_S(parent):
    for i in range(len(parent)):
        if random.uniform(0, 1) < mutation_rate:
            parent[i] = random.uniform(Max_S, Min_S)
        else:
            pass
    return parent

In [197]:
def mutation_M(parent):
    for i in range(len(parent)):
        if random.uniform(0, 1) < mutation_rate:
            parent[i] = random.uniform(Max_M, Min_M)
        else:
            pass
    return parent

In [198]:
def mutation_fuzzy(parent):
    for i in range(len(parent)):
        if random.uniform(0, 1) < mutation_rate:
            parent[i] = random.randint(0, 4) 
        else:
            pass
    return parent

In [199]:
def mutation_being_notList(parent):
    for i in range(len(parent[being])):
        if random.uniform(0, 1) < mutation_rate:
            parent[being][i] = parent[being][i] * -1 + 1
        else:
            pass
    
    for i in range(len(parent[not_list])):
        if random.uniform(0, 1) < mutation_rate:
            parent[not_list][i] = parent[not_list][i] * -1 + 1
        else:
            pass
        
    return parent

In [200]:
def mutation_term_choice(parent):
    for i in range(len(parent[rule][term_choice])):
        if random.uniform(0, 1) < mutation_rate:
            parent[rule][term_choice][i] = random.choice(parent[structure][i][linguistic_variable])
        else:
            pass
    return parent

In [201]:
def mutation(parent):
    for i in range(gen_num):
        parent[structure][i][linguistic_variable] = mutation_linguistic(parent[structure][i][linguistic_variable])
        parent[structure][i][type_Fuzzy_Set] = mutation_fuzzy(parent[structure][i][type_Fuzzy_Set])
        parent[structure][i][Paramerters_M] = mutation_M(parent[structure][i][Paramerters_M])
        parent[structure][i][Paramerters_S] = mutation_S(parent[structure][i][Paramerters_S])
    
    parent[rule][not_list] = mutation_being_notList(parent[rule])
    parent[rule][term_choice] = mutation_term_choice(parent)
    
    if random.uniform(0, 1) < mutation_rate:
        parent[rule][y] = parent[rule][y] * -1 + 1

    
    return parent

In [202]:
len(parent2[structure])

5

In [203]:
print(parent1)
print(parent2)
child1, child2 = crossover(parent1, parent2)
print(child1)
print(child2)
print(child1[structure][0][Paramerters_S])
print(child2[structure][0][Paramerters_S])
child1 = mutation(child1)
child2 = mutation(child2)
child1[structure][0][Paramerters_S].sort()
print(child1[structure][0][Paramerters_S])
print(child2[structure][0][Paramerters_S])

{'structure': [{'linguistic variable': ['very high', 'low', 'high', 'medium', 'medium'], 'S': [18.00092392148105, 35.5212714230438, 51.93577525190512, 25.07971419496726, 9.25746533301306], 'M': [-2.9755678646648036, -7.987661566111882, -5.237232611665057, 4.824482776105832, 5.703728156081404], 'fuzzy set': [3, 3, 3, 3, 1]}, {'linguistic variable': ['medium', 'low', 'high', 'high'], 'S': [62.35974419001193, 56.647564555088344, 60.28118707196227, 14.26498565300781], 'M': [2.7281048745419554, -3.221407874680124, -2.9932658385087443, -7.072109541499621], 'fuzzy set': [3, 4, 4, 3]}, {'linguistic variable': ['very low', 'very low', 'very low'], 'S': [45.63025312717126, 61.3954492402138, 63.60204123751237], 'M': [-0.4479337242560675, -0.4834080897254154, -0.6241543495818878], 'fuzzy set': [1, 1, 1]}, {'linguistic variable': ['very low', 'high', 'very low'], 'S': [4.540877237330177, 13.648949176276755, 20.007396678759022], 'M': [-1.1029198610632278, 1.0240100000421517, -8.103631140855908], 'fu

In [204]:

def isosceles_triangular_fuzzy(x, m, s):
    return np.max(np.min((x - m) / s, (m - x) / s), 0)


def trapezoids_of_Malzawie_fuzzy(x, m, s):
    return np.max(np.min((x - m) / s, 1), 0)


def gaussian_fuzzy(x, m, s):
    return np.exp(-0.5 * ((x - m) / s) ** 2)


def sigmoid_fuzzy(x, m, s):
    return 1 / (1 + np.exp((x - m) / s))
# def Fc(R,numberOfrule):


# def Fneg(Ruls,numberOfrule):
#     for i in range(numberOfrule):
#         pass

# def gR(xP, muA):
#     result = 1
#     for i in range(len(xP)):
#         result *= muA[i] * xP[i]
#     return result


# def gC(LOFL_xP, LOFL_muA, numberOfrule=5):  # nothing
#     result = 0
#     for i in range(len(LOFL_xP)):
#         result += gR(LOFL_xP[i], LOFL_muA[i])
#     return result


def Fc(LOFL_xP, LOFL_muA, numberOfrule):  #
    result = 0
    for i in range(len(LOFL_xP)):
        result += gR(LOFL_xP[i], LOFL_muA[i])
    return result


def Fneg(LOFL_xP, LOFL_muA, number_another_rule):   # r = number_another_rule

    return Fc(LOFL_xP, LOFL_muA, number_another_rule)


def CF(LOFL_xP, LOFL_muA, numberOfrule):  # also we are detect gole class is zero or one
    fneg_Rj = Fneg(LOFL_xP, LOFL_xP, abs(5574-numberOfrule))
    fc_Rj = Fc(LOFL_xP, LOFL_muA, numberOfrule)
    return (fc_Rj - fneg_Rj) / (fc_Rj + fneg_Rj)

In [205]:
def Gr(xP, parent):  # parent is one chromosome
    Gr = 1.0
    Mu_temp = []
    M = []
    S = []
    fuzzy_function = []   # [4, 3]
    indices_being = [j for j, x in enumerate(parent[rule][being]) if x == 0]
    indices_not = [j for j, x in enumerate(parent[rule][not_list]) if x == 1]
    for i in range(len(parent[structure])):
        if i in indices_being:
            pass
        else:
            # indices  list of index where have multi equal value  E.g == > [0, 1]
            indices_terms = [k for k, x in enumerate(parent[structure][i][linguistic_variable]) if x == parent[rule][term_choice][i]]
            
            for index in indices_terms:  # find the fuzzy set  E.g [4, 3]
                fuzzy_function.append(parent[structure][i][type_Fuzzy_Set][index])
                M.append(parent[structure][i][Paramerters_M][index])
                S.append(parent[structure][i][Paramerters_S][index])
                
            for j in range(len(fuzzy_function)): # select the function fuzzy
                if fuzzy_function[j] == 1:
                    Mu_temp.append(isosceles_triangular_fuzzy(xP[i], M[j], S[j]))
                elif fuzzy_function[j] == 2:
                    Mu_temp.append(trapezoids_of_Malzawie_fuzzy(xP[i], M[j], S[j]))
                elif fuzzy_function[j] == 3:
                    Mu_temp.append(gaussian_fuzzy(xP[i], M[j], S[j]))
                elif fuzzy_function[j] == 4:
                    Mu_temp.append(sigmoid_fuzzy(xP[i], M[j], S[j]))
                
                if i in indices_not:
                    Mu_temp[-1] = 1 - Mu_temp[-1]
            
            Gr *= (max(Mu_temp) * xP[i])
            Mu_temp.clear()
            fuzzy_function.clear()
            S.clear()
            M.clear()

    return Gr

In [212]:
def fitness_function(parent):
    Fc = 0.0
    Fneg = 0.0
    for i in range(len(records_dim_reduced)):  
        if labels[i] == parent[rule][y]:
            Fc += Gr(records_dim_reduced[i], parent)
        else:
            Fneg += Gr(records_dim_reduced[i], parent)
    
    CF = (Fc - Fneg) / (Fneg + Fc)
    
    return CF

In [207]:
def evalate_fitness(population):
    for i in range(len(population)):
        population[i][fitness] = fitness_function(population[i])
    
    return population

In [208]:
def create_childs(population):
    new_population = []
    size = int(crossover_rate * len(population) / 2)
    for i in range(size):
        child1, child2 = crossover(population[2*i], population[2*i+1])
        child1 = mutation(child1)
        child2 = mutation(child2)
        new_population.append(child1)
        new_population.append(child2)
    
    new_population = evalate_fitness(new_population)
    
    return new_population

In [209]:
def select_surviver(population, new_generation):
    population.extend(new_generation)
    population.sort(key=lambda x: x[fitness], reverse=True)
    return population[:50]

In [210]:
def GA():
    population = create_chromosomes(num_of_chromosomes)
    population = evalate_fitness(population)
    population = population.sort(key=lambda x: x[fitness], reverse=True)
    
    for _ in range(num_of_generations):
        new_generation = create_childs(population)
        population = select_surviver(population, new_generation)
        
        chart_fitness.append(sum(population, key=lambda x: x[fitness]) / num_of_chromosomes)
        
    chart()
    chart_fitness.clear()
    
    return max(population, key=lambda x: x[fitness])

In [213]:
print('Best rule for detecting spam emails:\n', GA())

AxisError: axis 1 is out of bounds for array of dimension 0